export async function updateV(self) {
	const varList = [
		{ variableId: 'amp_type', name: 'Amp Type' },
		{ variableId: 'amp_name', name: 'Amp Name' },
		{ variableId: 'amp_firmware', name: 'Amp Firmware' },
		{ variableId: 'amp_power', name: 'Amp Power' },
		{ variableId: 'amp_power_hours', name: 'Amp Power Hours' },
		{ variableId: 'amp_mute_0', name: 'Mute Ch1' },
		{ variableId: 'amp_mute_1', name: 'Mute Ch2' },
		{ variableId: 'amp_mute_2', name: 'Mute Ch3' },
		{ variableId: 'amp_mute_3', name: 'Mute Ch4' },
		{ variableId: 'amp_ch_0_eq_1', name: 'EQ Bypass Ch1 EQ1' },
		{ variableId: 'amp_ch_1_eq_1', name: 'EQ Bypass Ch2 EQ1' },
		{ variableId: 'amp_ch_2_eq_1', name: 'EQ Bypass Ch3 EQ1' },
		{ variableId: 'amp_ch_3_eq_1', name: 'EQ Bypass Ch4 EQ1' },
		{ variableId: 'amp_delay_ch_0', name: 'Delay Ch1' },
		{ variableId: 'amp_delay_ch_1', name: 'Delay Ch2' },
		{ variableId: 'amp_delay_ch_2', name: 'Delay Ch3' },
		{ variableId: 'amp_delay_ch_3', name: 'Delay Ch4' },
		{ variableId: 'amp_delay_bypass_ch_0', name: 'Delay Bypass Ch1' },
		{ variableId: 'amp_delay_bypass_ch_1', name: 'Delay Bypass Ch2' },
		{ variableId: 'amp_delay_bypass_ch_2', name: 'Delay Bypass Ch3' },
		{ variableId: 'amp_delay_bypass_ch_3', name: 'Delay Bypass Ch4' },
		{ variableId: 'amp_speaker_id_ch_0', name: 'Speaker ID Ch1' },
		{ variableId: 'amp_speaker_id_ch_1', name: 'Speaker ID Ch2' },
		{ variableId: 'amp_speaker_id_ch_2', name: 'Speaker ID Ch3' },
		{ variableId: 'amp_speaker_id_ch_3', name: 'Speaker ID Ch4' },
		{ variableId: 'amp_speaker_name_ch_0', name: 'Speaker Name Ch1' },
		{ variableId: 'amp_speaker_name_ch_1', name: 'Speaker Name Ch2' },
		{ variableId: 'amp_speaker_name_ch_2', name: 'Speaker Name Ch3' },
		{ variableId: 'amp_speaker_name_ch_3', name: 'Speaker Name Ch4' },
		{ variableId: 'amp_speaker_names', name: 'Speaker Types' },
		{ variableId: 'amp_channel_level_1', name: 'Channel Level 1' },
		{ variableId: 'amp_channel_level_2', name: 'Channel Level 2' },
		{ variableId: 'amp_channel_level_3', name: 'Channel Level 3' },
		{ variableId: 'amp_channel_level_4', name: 'Channel Level 4' },
		{ variableId: 'amp_input_gain_enable', name: 'Input Gain Enable' },
		{ variableId: 'amp_input_gain_ch_0', name: 'Input Gain Ch1' },
		{ variableId: 'amp_input_gain_ch_1', name: 'Input Gain Ch2' },
		{ variableId: 'amp_input_gain_ch_2', name: 'Input Gain Ch3' },
		{ variableId: 'amp_input_gain_ch_3', name: 'Input Gain Ch4' },
	]

	if (self.type != '5D') {
		varList.push(
			{ variableId: 'amp_preset_last', name: 'Last Amp Preset Recall' },
			{ variableId: 'amp_preset_1', name: 'Amp Preset User 1' },
			{ variableId: 'amp_preset_2', name: 'Amp Preset User 2' },
			{ variableId: 'amp_preset_3', name: 'Amp Preset User 3' },
			{ variableId: 'amp_preset_4', name: 'Amp Preset User 4' },
			{ variableId: 'amp_preset_5', name: 'Amp Preset User 5' },
			{ variableId: 'amp_preset_6', name: 'Amp Preset User 6' },
			{ variableId: 'amp_preset_7', name: 'Amp Preset User 7' },
			{ variableId: 'amp_preset_8', name: 'Amp Preset User 8' },
			{ variableId: 'amp_preset_9', name: 'Amp Preset User 9' },
			{ variableId: 'amp_preset_10', name: 'Amp Preset Alarm 1' },
			{ variableId: 'amp_preset_11', name: 'Amp Preset Alarm 2' },
			{ variableId: 'amp_preset_12', name: 'Amp Preset Alarm 3' },
			{ variableId: 'amp_preset_13', name: 'Amp Preset Backup 1' },
			{ variableId: 'amp_preset_14', name: 'Amp Preset Backup 2' },
			{ variableId: 'amp_preset_15', name: 'Amp Preset Backup 3' },
			{ variableId: 'amp_preset_state_1', name: 'Amp Preset State User 1' },
			{ variableId: 'amp_preset_state_2', name: 'Amp Preset State User 2' },
			{ variableId: 'amp_preset_state_3', name: 'Amp Preset State User 3' },
			{ variableId: 'amp_preset_state_4', name: 'Amp Preset State User 4' },
			{ variableId: 'amp_preset_state_5', name: 'Amp Preset State User 5' },
			{ variableId: 'amp_preset_state_6', name: 'Amp Preset State User 6' },
			{ variableId: 'amp_preset_state_7', name: 'Amp Preset State User 7' },
			{ variableId: 'amp_preset_state_8', name: 'Amp Preset State User 8' },
			{ variableId: 'amp_preset_state_9', name: 'Amp Preset State User 9' },
			{ variableId: 'amp_preset_state_10', name: 'Amp Preset State Alarm 1' },
			{ variableId: 'amp_preset_state_11', name: 'Amp Preset State Alarm 2' },
			{ variableId: 'amp_preset_state_12', name: 'Amp Preset State Alarm 3' },
			{ variableId: 'amp_preset_state_13', name: 'Amp Preset State Backup 1' },
			{ variableId: 'amp_preset_state_14', name: 'Amp Preset State Backup 2' },
			{ variableId: 'amp_preset_state_15', name: 'Amp Preset State Backup 3' },
			{ variableId: 'amp_ch_0_eq_2', name: 'EQ Bypass Ch1 EQ2' },
			{ variableId: 'amp_ch_1_eq_2', name: 'EQ Bypass Ch2 EQ2' },
			{ variableId: 'amp_ch_2_eq_2', name: 'EQ Bypass Ch3 EQ2' },
			{ variableId: 'amp_ch_3_eq_2', name: 'EQ Bypass Ch4 EQ2' },
		)
	}

	self.setVariableDefinitions(varList)
}
